[package]
name = "mongo_gest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.2.1"
tokio = "1"
terminal-menu = "2.0.3"
